global:
  domain: argocd.ajbarbosa.xyz

# Server component configuration
server:
  serviceAccount:
    create: false
    name: argocd-server
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/backend-protocol: HTTPS
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:920278691034:certificate/30962d3f-3710-42b7-9f4a-7547389e50ea
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/group.name: "shared-alb"
  service:
    type: ClusterIP

# Application controller configuration
controller:
  serviceAccount:
    create: false
    name: argocd-application-controller

# Repo server configuration
repoServer:
  serviceAccount:
    create: false
    name: argocd-repo-server

# ApplicationSet controller configuration
applicationSet:
  serviceAccount:
    create: false
    name: argocd-applicationset-controller